# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  body_size_limit: 15MB
  sample_limit: 1500
  target_limit: 30
  label_limit: 30
  label_name_length_limit: 200
  label_value_length_limit: 200
  query_log_file: query.log
  scrape_failure_log_file: fail.log

remote_write:
  - url: http://localhost:9090/api/v1/write
    name: remote_write_1

scrape_configs:
  - job_name: 'prometheus'  # Self-monitoring configuration
    static_configs:
      - targets: ['localhost:9090']  # Prometheus's own metrics endpoint
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080
