
services:

  #############################
  ## demo containers & load generation
  nginx_demo_container1:
    image: nginx:mainline
    expose:
      - "80/tcp"
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    labels:
      org.label-schema.group: "load-test"
      watchtower.enable: "true"

  nginx_demo_container2:
    image: nginx:mainline
    expose:
      - "80/tcp"
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    labels:
      org.label-schema.group: "load-test"
      watchtower.enable: "true"

  vegeta_demo_load1:
    image: jujhars13/vegeta:latest
    volumes:
      - ./backend/dummy_nginx_load.sh:/dummy_nginx_load.sh:ro
    entrypoint: ["/dummy_nginx_load.sh"]
    environment:
      - URL=nginx_demo_container1:80
    depends_on:
      - nginx_demo_container1
    labels:
      org.label-schema.group: "load-test"
      watchtower.enable: "true"

  vegeta_demo_load2:
    image: jujhars13/vegeta:latest
    volumes:
      - ./backend/dummy_nginx_load.sh:/dummy_nginx_load.sh:ro
    entrypoint: ["/dummy_nginx_load.sh"]
    environment:
      - URL=nginx_demo_container2:80
    depends_on:
      - nginx_demo_container2
    labels:
      org.label-schema.group: "load-test"
      watchtower.enable: "true"
