version: "3.8"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - 8081:8080
    expose:
      - "8080/tcp"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    labels:
      org.label-schema.group: "observability"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    expose:
      - "9090/tcp"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    volumes:
      - ./backend/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    labels:
      org.label-schema.group: "observability"

  grafana:
    image: grafana/grafana:8.2.6
    volumes:
      - ./backend/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    expose:
      - "3000/tcp"
    depends_on:
      - prometheus
    labels:
      org.label-schema.group: "observability"

  #############################
  ## demo containers & load
  nginx_demo_container1:
    image: nginx:1.21
    expose:
      - "80/tcp"
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    labels:
      org.label-schema.group: "load-test"

  nginx_demo_container2:
    image: nginx:1.21
    expose:
      - "80/tcp"
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    labels:
      org.label-schema.group: "load-test"

  vegeta_demo_load1:
    image: jujhars13/vegeta:latest
    volumes:
      - ./backend/dummy_nginx_load.sh:/dummy_nginx_load.sh:ro
    entrypoint: ["/dummy_nginx_load.sh"]
    environment:
      - URL=nginx_demo_container1:80
    depends_on:
      - nginx_demo_container1
    labels:
      org.label-schema.group: "load-test"

  vegeta_demo_load2:
    image: jujhars13/vegeta:latest
    volumes:
      - ./backend/dummy_nginx_load.sh:/dummy_nginx_load.sh:ro
    entrypoint: ["/dummy_nginx_load.sh"]
    environment:
      - URL=nginx_demo_container2:80
    depends_on:
      - nginx_demo_container2
    labels:
      org.label-schema.group: "load-test"
